### ISSUE TITLE
Mobile layout > Header > Static button width causing layout issues

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#121]
## Describe the bug
The width of the buttons is being set to a static width of `75vw` which is causing it to overflow it's parent in some instances.

## To Reproduce
1. Go to home page
2. See the Join Waitlist and Learn More buttons
4. See issue

## Expected behavior
These buttons should be set to % of parents, not relative viewport value on mobile devices

## Screenshots
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/d93c19e4-150c-4325-a6b7-d4c9a3f0a080)

## Additional context

The problem is caused by this code in `component/Button.css`

```css
@media screen and (max-width: 768px)
.button-big, .button-big-outline {
    width: 75vw;
}
```
